### ISSUE TITLE
PlutoTV issue with commercials

### ISSUE THREAD

**Issue by stuckinthe** [matthuisman/slyguy.addons#122]
I'm using PlutoTV along with IPTVMerge on a Rpi3+ running Arch and Kodi 19.3. With the show adverts, I have tried using them both on and off. Either way causes a problem with the show. Sometimes I get a black screen with sound and it doesn't return to the show. Sometimes it shows part of the commercial and then the image freezes with the sound still going and I can hear the sound from the program after the commercials but the screen is frozen. Looks like there is an issue with detection or the hand off from show to commercial or whatever you put in its place.

Also, IPTV Merge doesn't work with Python 3.10.2-1 so I had to roll back to 3.9.9

**Comment by matthuisman** [comment]
Commercials issue is out of my hand. It'll need be fixed in ffmpeg or
inputstream adaptive.

I'll take a look at the python 3.10 issue

**Comment by kevwag** [comment]
I've been having similar problems, both with Pluto TV and Samsung TV Plus on my CoreELEC box (CE-20 Nexus Nightly Builds).
Usually, things freeze up at the end of an ad break when the show should come back.

On Pluto TV I can usually overcome the freeze by pressing the left arrow key to advance a few frames but this isn't possible in Samsung TV plus because some of the channels don't work unless HLS is turned off and this also disables the timeshift function on the player.

If I try to stop playback or change to another channel while the playback is frozen, Kodi locks up completely, remains unresponsive for about a minute before rebooting the system.

@matthuisman  I also have a question that's unrelated to the issue but have no other way to contact you and don't want to open an issue just to enquire:
Do you have any plans to add sections for the on-demand content of Pluto TV and Stirr to the respective addons? It would be awesome if you could :)

**Comment by matthuisman** [comment]
closing this as it requires work in inputstream adaptive or kodi core. 
Also suggest trying to turn off framerate matching as that get triggers every advert
