### ISSUE TITLE
[HBO MAX] - Kodi 18.7 - no subs

### ISSUE THREAD

**Issue by Kijektom** [matthuisman/slyguy.addons#150]
Hello everyone,
I'm using Kodi 18.7 on a Raspberry Pi.
Unfortunately, it is not possible to install the newer Kodi on a Raspberry.

I am trying to select subtitles, unfortunately, they are not available.
I checked the same installation on a Kodi 19 computer and it works fine so the subtitle problem seems to be related to Kodi 18.7.

Can it be fixed somehow?

I would love to update the Kodi, unfortunately, it is not possible to install the newer Kodi on the Raspberry. #

**Comment by dzyndzla** [comment]
I probably face the same issue having the same setup; following discussion from [reddit](https://www.reddit.com/r/MattHuisman/comments/jvpgee/hbo_max_kodi_addon/i16uftw/?utm_source=reddit&utm_medium=web2x&context=3) I'm leaving a comment instead of opening a new issue.

`I have a Kodi 18.7 @ Retropie on RPi3B+; I can't force addon to display any subs, option to choose Subs is greyed out. I checked on Kodi 19.4 on LibreELEC and on desktop Manjaro with same subs setup and it works in both cases. Is it possible that Kodi 18.7 has some issies with that addon? WV library is 2252.0; subs settings are: default subs: pl, subs allow list: en,pl, inlude forced+nonforced subs are set to on but i crosschecked many other combinations without result.`

**Comment by Firesphere** [comment]
Are you using a manual installation of Kodi, on top of Raspberry Pi OS?

Since LibreELEC has the latest Kodi no problem, as far as I've experienced

**Comment by matthuisman** [comment]
@firesphere
Latest Libreelec will be Kodi 19. This is Kodi 18 issue which I suspect won't be able to be fixed. But I will take a look when I get a chance
