### ISSUE TITLE
Foxtel Go resolution now only 576

### ISSUE THREAD

**Issue by guy99au** [matthuisman/slyguy.addons#237]
Live streams and VOD now only playing at 576. Is it the addon or has Foxtel pulled the plug on HD for Foxtel Go?

**Comment by guy99au** [comment]
It's definitely the addon. Tried it on another box still running v0.9.1 - 720 for live channels and VOD at 1080. How can I roll back to the previous version?

**Comment by matthuisman** [comment]
Wednesday night is patch night for me so expect fixed tonight :)

**Comment by matthuisman** [comment]
should be fixed now with [v0.9.3](https://github.com/matthuisman/slyguy.addons/commit/41671fbf65c6b10fe106a2caa1944c4599a85cdd).

The above was changed due to https://github.com/matthuisman/slyguy.addons/issues/233
and the endpoint we were using actually stopped working.
Appears it was actually a temporary issue with foxtel go and came back - so we can now use it again

**Comment by matthuisman** [comment]
looks like reverting the changes broke VOD again.
https://github.com/matthuisman/slyguy.addons/issues/233

**Comment by guy99au** [comment]
Thanks Matt. That fixed it. No issues with VOD for me.
