### ISSUE TITLE
[Paramount+] Video not starting (Germany)

### ISSUE THREAD

**Issue by heini** [matthuisman/slyguy.addons#323]
Hi,

just activated P+ and verified it's working in the browser (Debian). Installed the latest Kodi addon (Thanks a lot!), entered login data, but when trying to watch something (Yellowstone, in case it matters), I get the spinning wheel, and the playback time already starts counting, but neither audio nor video starts.

Also seems that it only lists the English titles instead of the German ones, as it is in the browser.

**Comment by Yohoki** [comment]
Looks like something might have changed on Paramount's end. It also doesn't work on english in NA. Everything seems to work fine, except playing videos.

Logging in and the User list still loads. Video lists still load. Just playing videos doesn't work.

**Comment by Yohoki** [comment]
Another note, my daughter told me that Paramount WAS working on her tablet. I checked and it IS working there. So, I pulled logs from each of my devices. Hopefully it helps? I wouldn't know what to look for.

[kodi(Tablet-Android-Working).log](https://github.com/matthuisman/slyguy.addons/files/10312373/kodi.Tablet-Android-Working.log)
[kodi(Laptop-LibreElec-NotWork).log](https://github.com/matthuisman/slyguy.addons/files/10312372/kodi.Laptop-LibreElec-NotWork.log)
[kodi(desktop-Win10-NotWork).log](https://github.com/matthuisman/slyguy.addons/files/10312374/kodi.desktop-Win10-NotWork.log)

**Comment by heini** [comment]
Works for me now, applying the latest update. Video starts playing, incl. (German) audio. Only remaining (minor) issue is that the titles are still shown in English (while browser shows German titles).

**Comment by matthuisman** [comment]
Oh excellent

**Comment by heini** [comment]
> #333 is the issue for the language

Thanks, will subscribe to it...

**Comment by Yohoki** [comment]
unfortunately my builds are still broken. Should I make a new issue for that?

**Comment by matthuisman** [comment]
Oh. So same issue as this persists for.you. I've reopened this

**Comment by Yohoki** [comment]
Yep. Though, may be a different issue, since mine is set to English, not German.

I left logs the 3rd post. It's odd, because my kids' tablets are still working, but the 2 PCs (Win10/LibreELEC) are not. I can pull 0.6.1 logs if you need.

**Comment by Yohoki** [comment]
It's almost been a year, and I don't know when it started working again, but paramount videos started showing an error message instead of just failing to play the videos. The error message pointed me to the logs, which showed
 - CVideoPlayer::OpenInputStream - error opening [plugin://slyguy.paramount.plus/...]
 
 This wasn't immediately clear what needed fixing, but reinstalling widevine seems to have fixed it. I don't know what originally broke the add-on for me, but it might have been the oddly named version of widevine that was installed for some reason.
 
 Since OP's issue was fixed ages ago and mine is now fixed, this issue can be closed.

**Comment by matthuisman** [comment]
Thanks for letting me know. Closing :)
