### ISSUE TITLE
Subtitles out of the standard in HBO Max

### ISSUE THREAD

**Issue by DoctorBR** [matthuisman/slyguy.addons#38]
I am using HBO MAX **in Brazil** with Kodi 18.9 installed in a Xiaomi Mi Box, and even 4K content with HDR works without problem, except for the fact that I need to leave only stereo.

But subtitles are out of the standard **(large and with 4 lines).** In the add-ons Netflix and Prime Video that does not happen (in them appear only 2 lines).

![Screenshot_20210727-192145 - Add-on HBO Max (legendas no Kodi)](https://user-images.githubusercontent.com/25212010/127242498-678316b5-f883-4bda-828e-6b99e39b7fff.png)

I also miss the content on "My List" (in the add-on it gets empty **(no items)).**

Is there anything to do to avoid these problems?

**Comment by matthuisman** [comment]
those subs are built-in to the video stream.. so I can't change them.
But that is why they display differently.

ill look into "My list"

**Comment by matthuisman** [comment]
looking more at this, I think you just need to change your subtitle settings in kodi itself....
You need to change your Subtitle font settings in kodi to make them smaller.
These are just normal WEBVTT subtitles

As for over 4x lines - that is just how it is.
It's getting converted from ttml which have big overlapping issues to WEBVTT.
if the subtitle has the same timestamp, its put on the next line (instead of overlapping)
I assume it is different people speaking that?

**Comment by DoctorBR** [comment]
After the corrections the subtitles improved a lot, but another problem emerged: the dialogues are not being separated (see image below). 

![Screenshot_20210805-074241 - ETRI02](https://user-images.githubusercontent.com/25212010/128447367-fe689986-b057-4791-9a0d-cd579bde656c.png)

The correct (default) would be 2 lines.
I do not know if it's important, but I'm using osmosis to create the STRM files.

**Comment by matthuisman** [comment]
hmmm, i think it will be either all separate on separate lines or all on 1 line
ill have a look at that specific case

**Comment by matthuisman** [comment]
ok, 0.38.5 of slyguy common should fix that.
Now if it's merging a line and that line starts with a -, it'll put it on a new line
