### ISSUE TITLE
Unable to play udemy lectures

### ISSUE THREAD

**Issue by hollimaple** [matthuisman/slyguy.addons#479]
Some lectures cannot be played on udemy.
We know that we are in a situation where we cannot replay one lecture at a time.
Is there any way to make it possible to play them back?
We would like to help get information out about what is happening.

Translated from Japanese to English with a translator. Sorry.

**Comment by matthuisman** [comment]
please provide full kodi debug log showing the error that is happening

**Comment by hollimaple** [comment]
I will send you the suspicious part.

2023-06-16 20:34:33.641 T:4069    error <general>: script.module.slyguy - Invalid m3u8
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.slyguy/resources/lib/proxy.py", line 269, in do_GET
                                                       self._parse_m3u8(response)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.slyguy/resources/lib/proxy.py", line 1200, in _parse_m3u8
                                                       raise Exception('Invalid m3u8')
                                                   Exception: Invalid m3u8

**Comment by hollimaple** [comment]
[kodi.log](https://github.com/matthuisman/slyguy.addons/files/11769810/kodi.log)

I'll send you the full version.

I have tried it on Android, Windows, and Fire TV and all have the same symptoms.

**Comment by lundeen-bryan** [comment]
I might be having a similar problem but if this issue is resolved and I can't play videos, then I'll send you my kodi.log. I'm not sure exactly how to do that since my device is on firestick but I think there's a way to remote into it and pull the log. 
When clicking "My Courses" it says 
KeyError: 'results'
File "plugin.py", line 70, in my_courses
  items = _process_courses(data['results'])

I could type out the whole error but I'm not sure if that's even going to be helpful. 

Let me know if you want me to submit a brand new separate issue ticket for this. 

Thank you so much for the extension, it's been really great to learn from.

**Comment by matthuisman** [comment]
@hollimaple i just updated the addon to [v0.10.2](https://github.com/matthuisman/slyguy.addons/commit/e640b4772e83692fe4fb076196bb7ccb455bec2b)
Please try that version

**Comment by hollimaple** [comment]
I have confirmed that it is available for viewing.

Thank you for your response.
