### ISSUE TITLE
Question About Kodi Addons

### ISSUE THREAD

**Issue by dmbina** [matthuisman/slyguy.addons#532]
Hi @matthuisman,

Hope you are doing well!

I am a big fan of your work with the Kodi add-ons. Your add-ons repo has helped me so much with my mini Python apps. I want to create my own Kodi add-ons such as SlingTV, MGM+, AMC+, etc. What I am missing are the APIs. I was wondering if you could tell me how you capture the HTTPS traffic from the TV apps to collect the APIs.

Happy to discuss this over a cup of coffee (that I'll buy for you :)).

**Comment by matthuisman** [comment]
Android app + https://frida.re/ :)

**Comment by dmbina** [comment]
Thanks! Don't you use apps from Android TV to get APIs through a proxy? Or you just use Android app from Android Emulator + frida + proxy (like HTTP Toolkit)?

**Comment by matthuisman** [comment]
rooted shield can run frida :) 
or android emulator but that usually wont work that well
or even a rooted mobile can run android tv apps sometimes

**Comment by dmbina** [comment]
That's really good to know! How do you calculate the OAuth signature that's needed for API authentication? For example, for Udemy, you were able to calculate the upow. Do you decompile or disassemble the APK to see the JS code to find out how the signature or upow is calculated?

**Comment by matthuisman** [comment]
i cant recall udemy to be honest. i think that was using the JS from their website / app and just working through it. 
Some stuff is hard and time consuming!

**Comment by dmbina** [comment]
I feel you on that! Last questions:
1. What do you mean by "rooted shield"? Nvidia Shield Android TV?
2. Have you ever tried to bypass any captcha (reCAPTCHA) or Cloudflare to log in to websites?
3. Do you accept Kodi add-on requests from people?

**Comment by matthuisman** [comment]
1) shield android tv pro i think they provide a rooted image that you can flash (wont work with tube)
2) nope. Thats why i use android tv apps as they cant (as far as i know) do browser login
   Worse case they use the device code login so i use that if cant do email/pass. Plus its easier usually.
3) I do. Just as a github issue. I usually go for the bigger platforms that dont have existing addons

Doing the login / auth / playback is actually my favourite part of addons.
Dont know why - maybe because challenge?
I get bored when doing the content browsing stuff. Plus its really annoying trying to translate touch / horizontal / dynamic interfaces into kodis plugin vertical / static interface.  But think i now have the best approach with the tools we are given

**Comment by dmbina** [comment]
Yes, I also like doing the signin / auth / capture because you have to decompile or disassemble the apps to reverse engineer. 
I also want to use android tv apps but I am not able to capture HTTPS to intercept APIs. Do you use the Android TV apps them from hardware streaming devices like Shield Android TV, Firestick, etc.? Or do you use them on Android TV from Android Studio?
