### ISSUE TITLE
Stremium addon freezes during commercial breaks when viewing Philo channels

### ISSUE THREAD

**Issue by Powersurge** [matthuisman/slyguy.addons#60]
[crashlog.txt](https://github.com/matthuisman/slyguy.addons/files/7110959/crashlog.txt)
Hi, I have tested with several Philo channels and whenever there is a commercial break, the addon freezes up. I can get out of it by hitting the stop button, but if I try to play the channel again then Kodi crashes and this continues to happen until the show is back on. I have tried different picture quality settings but it didn't make a difference. I also tried watching a channel from within the Stremium addon and from the TV menu and that didn't make a difference either. I am running LibreELEC 10 on a Raspberry Pi 4.

Update: It doesn't just freeze up on commercials. I was watching Two and a Half Men on TV Land just now and it froze up during the middle of the show.

**Comment by mfreeman72** [comment]
I've also seen this happen frequently. It happens most often coming out of a show into a commercial break, or coming out of one commercial into another. It freezes and never returns until I manually stop the stream and restart it. This isn't on every commercial or commercial break, but most of them. On occasion (very infrequently), it also freezes in the middle of a show instead of at the commercial break, but this seems a little different. If I leave it running when that happens, it will eventually try to re-buffer repeatedly, with small spurts of played content for a second or so in between buffering sessions. I'll try to get a log and post it here when I get a chance.

**Comment by Powersurge** [comment]
I have noticed that since version 0.1.5 of this addon has been released, when I go to view a channel I now get a message saying "You must have at least Stremium Basic to watch channels from Philo. Please visit www.stremium.com/signup to sign up." Are there any Stremium Basic subscribers that are experiencing any of the issues mentioned above?

**Comment by matthuisman** [comment]
@Powersurge 
See here
https://github.com/matthuisman/slyguy.addons/issues/93

Basically you need to pay stremium now to use providers

**Comment by Powersurge** [comment]
Thank you, Matt! I think I will just continue to use my Roku to watch Philo channels for now. I'll keep my eyes on [this addon](https://github.com/d21spike/plugin.video.philo) and anything similar that might eventually come out.
