### ISSUE TITLE
[Optus Sport] Asset with id osXXXXX was not found

### ISSUE THREAD

**Issue by AllTinker-Lance** [matthuisman/slyguy.addons#669]
Live channels and main replays work fine, but selecting something from (for instance) `News & Articles -> Trending` results in the error.

Has the path changed for these particular videos perhaps?

Error stems from `plugin.video.optus.sport\resources\lib\api.py`, line 154.

Running Kodi 20.3, latest Optus plugin (0.8.6), slightly older Common (0.76.2).

Thanks!

**Comment by matthuisman** [comment]
haha - its because those news items are not videos :)
eg. https://sport.optus.com.au/news/laliga/os69101/barcelona-villarreal-eight-goal-thriller-second-defeat-four-days
https://sport.optus.com.au/news/all/os69098/postecoglous-offers-sobering-spurs-wake-up-call-after-lacklustre-city-defeat

I'll see if i can filter them out :)

**Comment by matthuisman** [comment]
instead of filtering, i decided to support them
[plugin.video.optus.sport -> v0.8.7](https://github.com/matthuisman/slyguy.addons/commit/d9e3457968e46be49ba61860f0102a6731dce55f) will now show articles in a textbox
