### ISSUE TITLE
Some Disney+ shows give 'durationMS' error

### ISSUE THREAD

**Issue by jgslade** [matthuisman/slyguy.addons#751]
Some of the shows we've been watching on disney+ started giving KeyError" 'durationMS' error code when trying to go into them.  I think they are all hulu on disney+ shows, specific examples that we've been getting this error on are Animal Control, 911, and 911 Lone Star.

I am running version 21.0 of kodi and have auto updates setup for the disney+ addon.

I've attached the log file.
[kodi.log](https://github.com/matthuisman/slyguy.addons/files/15488732/kodi.log)

**Comment by matthuisman** [comment]
Thank you for the excellent bug report :)

1) provided specific shows
2) provided debug log

Only thing missing was your GEO, but i could reproduce using USA

Its now fixed in [slyguy.disney.plus -> v0.16.6](https://github.com/matthuisman/slyguy.addons/commit/95d4fce24005037ed39db98a61f2e6aa5116d05e)
